# Generated by Django 5.1.4 on 2024-12-19 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_name', models.CharField(max_length=300)),
                ('student_class', models.CharField(max_length=100)),
                ('student_roll_no', models.IntegerField()),
                ('student_In_time', models.DateTimeField()),
                ('student_Out_time', models.DateTimeField()),
                ('student_singnature', models.FileField(upload_to='singnature')),
                ('student_image', models.FileField(upload_to='image')),
            ],
        ),
    ]
