# Generated by Django 5.1.4 on 2024-12-19 12:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('studd', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Student',
            new_name='Students',
        ),
    ]
