# Generated by Django 5.1.4 on 2024-12-23 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studd', '0003_students_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='students',
            name='student_count_view',
            field=models.IntegerField(default=1),
        ),
    ]
