# Generated by Django 5.1.4 on 2025-01-03 12:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('studd', '0006_fake'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student_info',
            name='deapartment',
        ),
        migrations.DeleteModel(
            name='Department',
        ),
    ]
