# Generated by Django 5.1.4 on 2025-07-21 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studd', '0007_remove_student_info_deapartment_delete_department'),
    ]

    operations = [
        migrations.AlterField(
            model_name='students',
            name='student_Out_time',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
